import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { EVENT_CONFIG } from '../config';
export const Map = () => {
    return (_jsx("section", { className: "py-16 sm:py-20 lg:py-24 bg-gradient-to-b from-slate-50 to-white px-4 sm:px-6 lg:px-8", "aria-label": "Location map", children: _jsxs("div", { className: "max-w-5xl mx-auto", children: [_jsx("h2", { className: "text-3xl sm:text-4xl lg:text-5xl font-bold text-party-deep-blue mb-12 text-center", children: "Find Us" }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-8 items-center", children: [_jsxs("div", { className: "lg:col-span-1 space-y-6", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-party-deep-blue mb-2", children: "\uD83D\uDCCD Location" }), _jsx("p", { className: "text-slate-700", children: EVENT_CONFIG.location }), _jsx("p", { className: "text-sm text-slate-600 mt-2", children: EVENT_CONFIG.fullAddress })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-party-deep-blue mb-2", children: "\uD83D\uDE97 Getting There" }), _jsx("p", { className: "text-slate-700 text-sm mb-4", children: "Easy access by car or public transportation." }), _jsx("a", { href: EVENT_CONFIG.googleMapsDirectionsUrl, target: "_blank", rel: "noopener noreferrer", className: "inline-flex items-center px-6 py-3 bg-party-gold text-party-deep-blue font-bold rounded-lg hover:bg-yellow-400 transition-colors focus:outline-none focus:ring-2 focus:ring-party-gold focus:ring-offset-2", children: "Open in Google Maps \u2192" })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-xl font-bold text-party-deep-blue mb-2", children: "\u2139\uFE0F Parking" }), _jsx("p", { className: "text-slate-700 text-sm", children: "Parking available on-site. Please arrive early." })] })] }), _jsx("div", { className: "lg:col-span-2", children: _jsx("div", { className: "relative w-full overflow-hidden rounded-lg shadow-lg border-4 border-party-gold", style: { paddingBottom: '66.66%' }, children: _jsx("iframe", { src: EVENT_CONFIG.googleMapsEmbedUrl, width: "100%", height: "100%", style: {
                                        border: 0,
                                        position: 'absolute',
                                        top: 0,
                                        left: 0,
                                    }, allowFullScreen: true, loading: "lazy", referrerPolicy: "no-referrer-when-downgrade", title: "Event location on Google Maps" }) }) })] })] }) }));
};
