import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { EVENT_CONFIG } from '../config';
import { Confetti } from './animations/Confetti';
export const Participation = () => {
    const [showConfetti, setShowConfetti] = useState(false);
    const handleSubmitClick = () => {
        setShowConfetti(true);
        setTimeout(() => setShowConfetti(false), 3000);
        window.open(EVENT_CONFIG.googleFormUrl, '_blank');
    };
    return (_jsxs("section", { className: "py-16 sm:py-20 lg:py-24 bg-gradient-to-b from-white to-slate-50 px-4 sm:px-6 lg:px-8", "aria-label": "How to participate", children: [showConfetti && _jsx(Confetti, {}), _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsx("h2", { className: "text-3xl sm:text-4xl lg:text-5xl font-bold text-party-deep-blue mb-8 text-center", children: "How to Participate" }), _jsx("p", { className: "text-lg text-slate-700 text-center mb-12 max-w-2xl mx-auto", children: "Have a performance, skill, or talent to share? Submit your contribution using the form below! We're looking for performers, speakers, artists, and more." }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-12", children: [_jsxs("div", { className: "text-center p-6 bg-blue-50 rounded-lg border-2 border-blue-200", children: [_jsx("div", { className: "text-3xl mb-2", children: "\uD83D\uDCDD" }), _jsx("h3", { className: "font-bold text-party-deep-blue mb-2", children: "Step 1: Fill Form" }), _jsx("p", { className: "text-sm text-slate-700", children: "Complete the submission form with details about your performance." })] }), _jsxs("div", { className: "text-center p-6 bg-purple-50 rounded-lg border-2 border-purple-200", children: [_jsx("div", { className: "text-3xl mb-2", children: "\u2705" }), _jsx("h3", { className: "font-bold text-party-deep-blue mb-2", children: "Step 2: Review" }), _jsx("p", { className: "text-sm text-slate-700", children: "Our team reviews submissions and confirms slot availability." })] }), _jsxs("div", { className: "text-center p-6 bg-indigo-50 rounded-lg border-2 border-indigo-200", children: [_jsx("div", { className: "text-3xl mb-2", children: "\uD83C\uDF89" }), _jsx("h3", { className: "font-bold text-party-deep-blue mb-2", children: "Step 3: Perform" }), _jsx("p", { className: "text-sm text-slate-700", children: "Showcase your talent at the New Year Party on January 20!" })] })] }), _jsxs("div", { className: "text-center", children: [_jsxs("button", { onClick: handleSubmitClick, className: "px-10 py-4 bg-gradient-to-r from-party-gold to-yellow-400 text-party-deep-blue font-bold text-xl rounded-lg hover:shadow-2xl hover:scale-105 transform transition-all duration-200 focus:outline-none focus:ring-4 focus:ring-yellow-300 focus:ring-offset-2", "aria-label": EVENT_CONFIG.googleFormLabel, children: ["\u2728 ", EVENT_CONFIG.googleFormLabel] }), _jsx("p", { className: "text-sm text-slate-600 mt-4", children: "Form opens in a new tab \u2022 No personal data collected on this site" })] })] })] }));
};
