import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { EVENT_CONFIG } from '../config';
export const RSVP = () => {
    const handleRsvpClick = () => {
        window.open(EVENT_CONFIG.googleFormUrl, '_blank');
    };
    return (_jsx("section", { className: "py-16 sm:py-20 lg:py-24 bg-gradient-to-r from-blue-600 to-indigo-700 px-4 sm:px-6 lg:px-8", "aria-label": "RSVP and tickets section", children: _jsxs("div", { className: "max-w-4xl mx-auto", children: [_jsx("h2", { className: "text-3xl sm:text-4xl lg:text-5xl font-bold text-white mb-8 text-center", children: "Secure Your Spot" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-8 mb-12", children: [_jsxs("div", { className: "bg-white/10 backdrop-blur-md rounded-lg p-8 border border-white/30", children: [_jsx("h3", { className: "text-2xl font-bold text-party-gold mb-4", children: "\uD83C\uDFAB Limited Seats" }), _jsxs("div", { className: "text-white space-y-4", children: [_jsxs("p", { children: [_jsx("span", { className: "block text-sm text-white/70", children: "Total Capacity" }), _jsx("span", { className: "text-3xl font-bold", children: EVENT_CONFIG.totalSeats })] }), _jsxs("p", { children: [_jsx("span", { className: "block text-sm text-white/70", children: "Remaining Seats" }), _jsx("span", { className: "text-3xl font-bold text-party-gold", children: EVENT_CONFIG.remainingSeats })] }), _jsx("div", { className: "w-full bg-white/20 rounded-full h-3 overflow-hidden", children: _jsx("div", { className: "bg-gradient-to-r from-party-gold to-yellow-400 h-full", style: {
                                                    width: `${(EVENT_CONFIG.remainingSeats / EVENT_CONFIG.totalSeats) * 100}%`,
                                                } }) }), _jsxs("p", { className: "text-sm text-white/70", children: [Math.round((EVENT_CONFIG.remainingSeats / EVENT_CONFIG.totalSeats) * 100), "% capacity available"] })] })] }), _jsxs("div", { className: "bg-white/10 backdrop-blur-md rounded-lg p-8 border border-white/30", children: [_jsx("h3", { className: "text-2xl font-bold text-party-gold mb-4", children: "\u2728 Quick Info" }), _jsxs("ul", { className: "text-white space-y-3", children: [_jsxs("li", { className: "flex items-start gap-3", children: [_jsx("span", { className: "text-party-gold text-lg", children: "\u2713" }), _jsx("span", { children: "No personal data collected on this site" })] }), _jsxs("li", { className: "flex items-start gap-3", children: [_jsx("span", { className: "text-party-gold text-lg", children: "\u2713" }), _jsx("span", { children: "Form handles all registration details securely" })] }), _jsxs("li", { className: "flex items-start gap-3", children: [_jsx("span", { className: "text-party-gold text-lg", children: "\u2713" }), _jsx("span", { children: "Confirmation sent via email" })] }), _jsxs("li", { className: "flex items-start gap-3", children: [_jsx("span", { className: "text-party-gold text-lg", children: "\u2713" }), _jsx("span", { children: "First come, first served basis" })] })] })] })] }), _jsxs("div", { className: "text-center", children: [_jsxs("button", { onClick: handleRsvpClick, className: "px-10 py-4 bg-party-gold text-party-deep-blue font-bold text-xl rounded-lg hover:shadow-2xl hover:scale-105 transform transition-all duration-200 focus:outline-none focus:ring-4 focus:ring-yellow-300 focus:ring-offset-2 focus:ring-offset-indigo-700", "aria-label": "RSVP and register", children: ["\uD83C\uDF89 ", EVENT_CONFIG.rsvpLabel] }), _jsx("p", { className: "text-white/70 text-sm mt-4", children: "Limited seats available \u2022 Register early!" })] })] }) }));
};
